FROM debian
RUN apt-get update -y && apt-get upgrade -y && \
	apt-get install wget bzip2 -y && \
	wget http://dl.4players.de/ts/releases/3.5.0/teamspeak3-server_linux_amd64-3.5.0.tar.bz2 && \
	bunzip2 teamspeak3-server_linux_amd64-3.5.0.tar.bz2 && \
	tar -xvf teamspeak3-server_linux_amd64-3.5.0.tar
ENV	TS3SERVER_LICENSE   "accept"
ENV	TS3SERVER_VERSION   "3.5.0"
CMD [ "sh", "teamspeak3-server_linux_amd64/ts3server_minimal_runscript.sh" ]
